#!/usr/bin/env bash

printf "[ %s: Calculate uniqueness with bbtools ]\n" \
    "$(date)"

# shellcheck disable=SC1091
source "src/sh/bash_header"
# shellcheck disable=SC1091
source "src/sh/io_parser"

# make outdir
outdir="$(dirname "${other_output}")"

# build command
java_ram=$((ram_limit/1000000000))"g"

cmd=( bin/bbtools/bbcountunique.sh threads="${max_cpus}" "-Xmx${java_ram}"
        "in=${input_fq}"
        "out=${other_output}"
        k=31 )

shopt -s extglob
printf "Final command line: "
printf "%s " "${cmd[@]//+([[:blank:]])/ }"
printf "\n"
shopt -u extglob

# run bbnorm
log_file="${outdir}/bbcountunique.log"
srun --ntasks=1 --cpus-per-task="${max_cpus}" --exclusive \
    --output="${log_file}" "${cmd[@]}" &

printf "[ %s: Waiting for bbcountunique to finish ]\n" "$(date)"
FAIL=0
fail_wait

# log metadata
metadata_file="${outdir}/uniqueness_histogram.METADATA.csv"
printf "[ %s: Logging metadata ]\n" "$(date)"
printf "metadata_file: %s\n" "${metadata_file}"
cat <<- _EOF_ > "${metadata_file}"
    Script,${0}
    branch,$(git rev-parse --abbrev-ref HEAD)
    hash,$(git rev-parse HEAD)
    date,$(date +%F)
    bbcountunique revision,$(bin/bbtools/bbcountunique.sh 2>&1 | sed '3q;d')
_EOF_

printf "[ %s: Done ]\n" "$(date)"

exit 0

