#!/usr/bin/env bash

printf "[ %s: Generate kmer coverage histogram ]\n" \
    "$(date)"


# shellcheck disable=SC1091
source "src/sh/bash_header"
# shellcheck disable=SC1091
source "src/sh/io_parser"

# make outdir
outdir="$(dirname "${other_output}")"
if [[ ! -d "${outdir}" ]]; then
    mkdir -p "${outdir}"
fi

# build command
java_ram=$((ram_limit/1000000000))"g"

cmd=( bin/bbtools/khist.sh threads="${max_cpus}" "-Xmx${java_ram}"
        "in=${input_fq}"
        "hist=${other_output}" )

shopt -s extglob
printf "Final command line: "
printf "%s " "${cmd[@]//+([[:blank:]])/ }"
printf "\n"
shopt -u extglob

# run bbnorm
log_file="${outdir}/khist.log"
"${cmd[@]}" 2> "${log_file}" &

printf "[ %s: Waiting for khist to finish ]\n" "$(date)"
FAIL=0
fail_wait

# log metadata
metadata_file="${outdir}/khist.METADATA.csv"
printf "[ %s: Logging metadata ]\n" "$(date)"
printf "metadata_file: %s\n" "${metadata_file}"
cat <<- _EOF_ > "${metadata_file}"
    Script,${0}
    branch,$(git rev-parse --abbrev-ref HEAD)
    hash,$(git rev-parse HEAD)
    date,$(date +%F)
    bbnorm revision,$(bin/bbtools/bbnorm.sh 2>&1 | sed '3q;d')
_EOF_

printf "[ %s: Done ]\n" "$(date)"

exit 0
